stages:
  convert_tdms:
    cmd: python src/data_preprocess/tdms_to_df.py data out
    deps:
      - src/data_preprocess/tdms_to_df.py
      - data
  rename_channels:
    cmd: python src/data_preprocess/rename_channels.py out intermidiate_files/rename_map.yaml out
    deps:
      - src/data_preprocess/rename_channels.py
      - out
      - intermidiate_files/rename_map.yaml
 
  merge_bench_line:
    cmd: python src/data_preprocess/merge_bench_line.py out out
    deps:
      - src/data_preprocess/merge_bench_line.py
      - out


  drop_columns:
    cmd: python src/data_preprocess/drop_columns.py out intermidiate_files/drop_file.txt out
    deps:
      - src/data_preprocess/drop_columns.py
      - out
      - intermidiate_files/drop_file.txt

  convert_to_csv:
    cmd: python src/data_preprocess/df_to_csv.py out csv_out
    deps:
      - src/data_preprocess/df_to_csv.py
      - out
  push_csv_to_warehouse:
    cmd: python src/data_preprocess/push_csv_out.py out csv_out
    deps:
      - src/data_preprocess/push_csv_out.py
      - data
      
      - out
 