name: churn-imbalanced-dataset-dvc
on: [push]
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
=======
>>>>>>> 4ffcd2441d0faeb65281993f9bcd4b937de113c8
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1

      - name: Upgrade pip
        run: python -m pip install --upgrade pip


      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: DVC Pipeline
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |

          dvc pull
          mkdir out
          mkdir csv_out
          dvc repro
          dvc add ./csv_out
          dvc push -r myremote2
