name: churn-imbalanced-dataset-dvc
on:
  push:
    branches:
      - verified
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1

      - name: Upgrade pip
        run: python -m pip install --upgrade pip


      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: DVC Pipeline
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |

          dvc pull -remote myremote
          mkdir out
          mkdir csv_out
          dvc repro
          dvc add ./csv_out
          
          git config --global user.email "iheb.kesraoui@nanoz-group.com"
          git config --global user.name "IhebKesraoui"
          git add .
          git commit -m "push the csv-out"
          dvc push -r myremote2
          git push origin verified
          
